spring.application.name=MonBlog

spring.datasource.url=jdbc:postgresql://localhost:5432/monblog
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Port du serveur
server.port=8080

# CORS (pour Next.js sur le port 3000)
app.cors.allowed-origins=*
