spring.application.name=FirstSpring
server.port=8181
spring.datasource.url=jdbc:mysql://localhost:3306/firstspring_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Laisser@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs